### ISSUE TITLE
Why does the latest build REQUIRE Json,NET >= 8.0.2?

### ISSUE THREAD

**Issue by ravensorb** [adamfisher/RestSharp.Serializers.Newtonsoft.Json#1]
Seems a little odd to require the absolute latest version of Json.NET unless it is really needed.  Is It?

**Comment by adamfisher** [comment]
It was just the version I had downloaded and built against at the time. Is there a reason not to upgrade?

**Comment by ravensorb** [comment]
There have been a fair amount of changes and a lot of people are still using v6 and v7 -- so I was just curious

**Comment by adamfisher** [comment]
I would accept pull requests or releases built against earlier versions.
