### ISSUE TITLE
NuGet package deprecation

### ISSUE THREAD

**Issue by alexeyzimarev** [adamfisher/RestSharp.Serializers.Newtonsoft.Json#12]
Thank you for helping the RestSharp community to use NewtonsoftJson serializer.

I have completed the work to support NewtonsoftJson in the core repository, but I decided to use a separate package. However, I am unable to publish the package because it conflicts with your package name. My package is called `RestSharp.NewtonsoftJson` and NuGet complains that it is too similar to yours.

Do you have an idea how can we solve this issue? I don't want to create issues for all those people who use your package.

**Comment by alexeyzimarev** [comment]
Since I got no follow up on this issue, we currently publish our package as `RestSharp.Serialization.NewtonsoftJson`. For me, it is not a problem.

However, since you marked your project as deprecated, maybe you can do a favour to developers that use RestSharp by making your package deprecated too and pointing to our official package?

**Comment by adamfisher** [comment]
@alexeyzimarev Done 👍 I archived this repo and deprecated it on NuGet.
