### ISSUE TITLE
No longer installs on .NET 4.6

### ISSUE THREAD

**Issue by harpsicord86** [adamfisher/RestSharp.Serializers.Newtonsoft.Json#6]
Hello,

I've been using this for a project of mine in VS 2015 via Nuget.  I've attempted to update the package but I keep getting an error message to say that the package is no longer compatible due to the package being no longer compatible with .NET 4.6 (see screenshot)

![image](https://user-images.githubusercontent.com/12445814/32232754-a8be67d4-be50-11e7-9892-a39b6903275b.png)

I've had a look at your package via Nuget Package Explorer and it seems its missing the necessary libraries for .NET 4.6.  Can this be rectified at all?

Many thanks

**Comment by lankymart** [comment]
It's dependent on .Net Standard 2.0 for some reason, which means I can't use it with the .Net Framework 4.5.2, gutted. Why make this so dependent on a specific .Net library?

**Comment by harpsicord86** [comment]
It works on the previous version released. That's the one I'm using at the moment. Unfortunately Nuget keeps reminding me there is an update I need to do which is frustrating 😡

**Comment by adamfisher** [comment]
Fixed in tag 1.4.0 now available on nuget.org.
