### ISSUE TITLE
Net standard support not working

### ISSUE THREAD

**Issue by screig** [adamfisher/RestSharp.Serializers.Newtonsoft.Json#7]
I think you need to update the dependency on Rest Sharp from 105.2.3 (which does not net standard) to 106.0.1.

Currently installing this package generates a warning:

> Package 'RestSharp 105.2.3' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

**Comment by adamfisher** [comment]
Fixed in tag 1.4.0 now available on nuget.org.
