### ISSUE TITLE
Binary incompatible with latest RestSharp

### ISSUE THREAD

**Issue by yar3333** [adamfisher/RestSharp.Serializers.Newtonsoft.Json#9]
After upgrading RestSharp to latest NuGet (v106.5.4), I have error in `new RestRequest("url", RestSharp.Method.GET);` about "Method not found".

**Comment by adamfisher** [comment]
I am not seeing an issue when I run the unit tests and I am able to build the project against v106.5.4. Can you make sure the nuget package does not contain a yellow warning symbol when you expand the dependencies node in your project.
